(cl:defpackage ros_essentials_cpp-srv
  (:use )
  (:export
   "ADDTWOINTS"
   "<ADDTWOINTS-REQUEST>"
   "ADDTWOINTS-REQUEST"
   "<ADDTWOINTS-RESPONSE>"
   "ADDTWOINTS-RESPONSE"
   "RECTANGLEAREASERVICE"
   "<RECTANGLEAREASERVICE-REQUEST>"
   "RECTANGLEAREASERVICE-REQUEST"
   "<RECTANGLEAREASERVICE-RESPONSE>"
   "RECTANGLEAREASERVICE-RESPONSE"
  ))

