// Generated by gencpp from file ros_essentials_cpp/AreaRectangleRequest.msg
// DO NOT EDIT!


#ifndef ROS_ESSENTIALS_CPP_MESSAGE_AREARECTANGLEREQUEST_H
#define ROS_ESSENTIALS_CPP_MESSAGE_AREARECTANGLEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_essentials_cpp
{
template <class ContainerAllocator>
struct AreaRectangleRequest_
{
  typedef AreaRectangleRequest_<ContainerAllocator> Type;

  AreaRectangleRequest_()
    : w(0.0)
    , h(0.0)  {
    }
  AreaRectangleRequest_(const ContainerAllocator& _alloc)
    : w(0.0)
    , h(0.0)  {
  (void)_alloc;
    }



   typedef double _w_type;
  _w_type w;

   typedef double _h_type;
  _h_type h;





  typedef boost::shared_ptr< ::ros_essentials_cpp::AreaRectangleRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_essentials_cpp::AreaRectangleRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AreaRectangleRequest_

typedef ::ros_essentials_cpp::AreaRectangleRequest_<std::allocator<void> > AreaRectangleRequest;

typedef boost::shared_ptr< ::ros_essentials_cpp::AreaRectangleRequest > AreaRectangleRequestPtr;
typedef boost::shared_ptr< ::ros_essentials_cpp::AreaRectangleRequest const> AreaRectangleRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_essentials_cpp::AreaRectangleRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_essentials_cpp::AreaRectangleRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_essentials_cpp

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'ros_essentials_cpp': ['/home/mathias/catkin_ws/src/ros_essentials_cpp/msg', '/home/mathias/catkin_ws/devel/share/ros_essentials_cpp/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ros_essentials_cpp::AreaRectangleRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_essentials_cpp::AreaRectangleRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_essentials_cpp::AreaRectangleRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_essentials_cpp::AreaRectangleRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_essentials_cpp::AreaRectangleRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_essentials_cpp::AreaRectangleRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_essentials_cpp::AreaRectangleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "77a0c743f6f1c6eff93d5316852c1de2";
  }

  static const char* value(const ::ros_essentials_cpp::AreaRectangleRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x77a0c743f6f1c6efULL;
  static const uint64_t static_value2 = 0xf93d5316852c1de2ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_essentials_cpp::AreaRectangleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_essentials_cpp/AreaRectangleRequest";
  }

  static const char* value(const ::ros_essentials_cpp::AreaRectangleRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_essentials_cpp::AreaRectangleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 w\n\
float64 h\n\
";
  }

  static const char* value(const ::ros_essentials_cpp::AreaRectangleRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_essentials_cpp::AreaRectangleRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.w);
      stream.next(m.h);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AreaRectangleRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_essentials_cpp::AreaRectangleRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_essentials_cpp::AreaRectangleRequest_<ContainerAllocator>& v)
  {
    s << indent << "w: ";
    Printer<double>::stream(s, indent + "  ", v.w);
    s << indent << "h: ";
    Printer<double>::stream(s, indent + "  ", v.h);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_ESSENTIALS_CPP_MESSAGE_AREARECTANGLEREQUEST_H
