// Generated by gencpp from file ros_essentials_cpp/AreaRectangle.msg
// DO NOT EDIT!


#ifndef ROS_ESSENTIALS_CPP_MESSAGE_AREARECTANGLE_H
#define ROS_ESSENTIALS_CPP_MESSAGE_AREARECTANGLE_H

#include <ros/service_traits.h>


#include <ros_essentials_cpp/AreaRectangleRequest.h>
#include <ros_essentials_cpp/AreaRectangleResponse.h>


namespace ros_essentials_cpp
{

struct AreaRectangle
{

typedef AreaRectangleRequest Request;
typedef AreaRectangleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AreaRectangle
} // namespace ros_essentials_cpp


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_essentials_cpp::AreaRectangle > {
  static const char* value()
  {
    return "acc8e380ccd62fbb09a40f869ff912e3";
  }

  static const char* value(const ::ros_essentials_cpp::AreaRectangle&) { return value(); }
};

template<>
struct DataType< ::ros_essentials_cpp::AreaRectangle > {
  static const char* value()
  {
    return "ros_essentials_cpp/AreaRectangle";
  }

  static const char* value(const ::ros_essentials_cpp::AreaRectangle&) { return value(); }
};


// service_traits::MD5Sum< ::ros_essentials_cpp::AreaRectangleRequest> should match 
// service_traits::MD5Sum< ::ros_essentials_cpp::AreaRectangle > 
template<>
struct MD5Sum< ::ros_essentials_cpp::AreaRectangleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_essentials_cpp::AreaRectangle >::value();
  }
  static const char* value(const ::ros_essentials_cpp::AreaRectangleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_essentials_cpp::AreaRectangleRequest> should match 
// service_traits::DataType< ::ros_essentials_cpp::AreaRectangle > 
template<>
struct DataType< ::ros_essentials_cpp::AreaRectangleRequest>
{
  static const char* value()
  {
    return DataType< ::ros_essentials_cpp::AreaRectangle >::value();
  }
  static const char* value(const ::ros_essentials_cpp::AreaRectangleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_essentials_cpp::AreaRectangleResponse> should match 
// service_traits::MD5Sum< ::ros_essentials_cpp::AreaRectangle > 
template<>
struct MD5Sum< ::ros_essentials_cpp::AreaRectangleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_essentials_cpp::AreaRectangle >::value();
  }
  static const char* value(const ::ros_essentials_cpp::AreaRectangleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_essentials_cpp::AreaRectangleResponse> should match 
// service_traits::DataType< ::ros_essentials_cpp::AreaRectangle > 
template<>
struct DataType< ::ros_essentials_cpp::AreaRectangleResponse>
{
  static const char* value()
  {
    return DataType< ::ros_essentials_cpp::AreaRectangle >::value();
  }
  static const char* value(const ::ros_essentials_cpp::AreaRectangleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_ESSENTIALS_CPP_MESSAGE_AREARECTANGLE_H
