// Generated by gencpp from file ros_essentials_cpp/RectangleAreaServiceRequest.msg
// DO NOT EDIT!


#ifndef ROS_ESSENTIALS_CPP_MESSAGE_RECTANGLEAREASERVICEREQUEST_H
#define ROS_ESSENTIALS_CPP_MESSAGE_RECTANGLEAREASERVICEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_essentials_cpp
{
template <class ContainerAllocator>
struct RectangleAreaServiceRequest_
{
  typedef RectangleAreaServiceRequest_<ContainerAllocator> Type;

  RectangleAreaServiceRequest_()
    : width(0.0)
    , height(0.0)  {
    }
  RectangleAreaServiceRequest_(const ContainerAllocator& _alloc)
    : width(0.0)
    , height(0.0)  {
  (void)_alloc;
    }



   typedef float _width_type;
  _width_type width;

   typedef float _height_type;
  _height_type height;





  typedef boost::shared_ptr< ::ros_essentials_cpp::RectangleAreaServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_essentials_cpp::RectangleAreaServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RectangleAreaServiceRequest_

typedef ::ros_essentials_cpp::RectangleAreaServiceRequest_<std::allocator<void> > RectangleAreaServiceRequest;

typedef boost::shared_ptr< ::ros_essentials_cpp::RectangleAreaServiceRequest > RectangleAreaServiceRequestPtr;
typedef boost::shared_ptr< ::ros_essentials_cpp::RectangleAreaServiceRequest const> RectangleAreaServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_essentials_cpp::RectangleAreaServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_essentials_cpp::RectangleAreaServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_essentials_cpp

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'ros_essentials_cpp': ['/home/mathias/catkin_ws/src/ros_essentials_cpp/msg', '/home/mathias/catkin_ws/devel/share/ros_essentials_cpp/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ros_essentials_cpp::RectangleAreaServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_essentials_cpp::RectangleAreaServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_essentials_cpp::RectangleAreaServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_essentials_cpp::RectangleAreaServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_essentials_cpp::RectangleAreaServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_essentials_cpp::RectangleAreaServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_essentials_cpp::RectangleAreaServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ed3043f094c99bdd8118bc5b0ddb14ba";
  }

  static const char* value(const ::ros_essentials_cpp::RectangleAreaServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xed3043f094c99bddULL;
  static const uint64_t static_value2 = 0x8118bc5b0ddb14baULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_essentials_cpp::RectangleAreaServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_essentials_cpp/RectangleAreaServiceRequest";
  }

  static const char* value(const ::ros_essentials_cpp::RectangleAreaServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_essentials_cpp::RectangleAreaServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 width\n\
float32 height\n\
";
  }

  static const char* value(const ::ros_essentials_cpp::RectangleAreaServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_essentials_cpp::RectangleAreaServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.width);
      stream.next(m.height);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RectangleAreaServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_essentials_cpp::RectangleAreaServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_essentials_cpp::RectangleAreaServiceRequest_<ContainerAllocator>& v)
  {
    s << indent << "width: ";
    Printer<float>::stream(s, indent + "  ", v.width);
    s << indent << "height: ";
    Printer<float>::stream(s, indent + "  ", v.height);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_ESSENTIALS_CPP_MESSAGE_RECTANGLEAREASERVICEREQUEST_H
