// Generated by gencpp from file ros_essentials_cpp/RectangleAreaService.msg
// DO NOT EDIT!


#ifndef ROS_ESSENTIALS_CPP_MESSAGE_RECTANGLEAREASERVICE_H
#define ROS_ESSENTIALS_CPP_MESSAGE_RECTANGLEAREASERVICE_H

#include <ros/service_traits.h>


#include <ros_essentials_cpp/RectangleAreaServiceRequest.h>
#include <ros_essentials_cpp/RectangleAreaServiceResponse.h>


namespace ros_essentials_cpp
{

struct RectangleAreaService
{

typedef RectangleAreaServiceRequest Request;
typedef RectangleAreaServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RectangleAreaService
} // namespace ros_essentials_cpp


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_essentials_cpp::RectangleAreaService > {
  static const char* value()
  {
    return "92e9c8f940da77dc3e1bc289f7dd146e";
  }

  static const char* value(const ::ros_essentials_cpp::RectangleAreaService&) { return value(); }
};

template<>
struct DataType< ::ros_essentials_cpp::RectangleAreaService > {
  static const char* value()
  {
    return "ros_essentials_cpp/RectangleAreaService";
  }

  static const char* value(const ::ros_essentials_cpp::RectangleAreaService&) { return value(); }
};


// service_traits::MD5Sum< ::ros_essentials_cpp::RectangleAreaServiceRequest> should match 
// service_traits::MD5Sum< ::ros_essentials_cpp::RectangleAreaService > 
template<>
struct MD5Sum< ::ros_essentials_cpp::RectangleAreaServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_essentials_cpp::RectangleAreaService >::value();
  }
  static const char* value(const ::ros_essentials_cpp::RectangleAreaServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_essentials_cpp::RectangleAreaServiceRequest> should match 
// service_traits::DataType< ::ros_essentials_cpp::RectangleAreaService > 
template<>
struct DataType< ::ros_essentials_cpp::RectangleAreaServiceRequest>
{
  static const char* value()
  {
    return DataType< ::ros_essentials_cpp::RectangleAreaService >::value();
  }
  static const char* value(const ::ros_essentials_cpp::RectangleAreaServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_essentials_cpp::RectangleAreaServiceResponse> should match 
// service_traits::MD5Sum< ::ros_essentials_cpp::RectangleAreaService > 
template<>
struct MD5Sum< ::ros_essentials_cpp::RectangleAreaServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_essentials_cpp::RectangleAreaService >::value();
  }
  static const char* value(const ::ros_essentials_cpp::RectangleAreaServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_essentials_cpp::RectangleAreaServiceResponse> should match 
// service_traits::DataType< ::ros_essentials_cpp::RectangleAreaService > 
template<>
struct DataType< ::ros_essentials_cpp::RectangleAreaServiceResponse>
{
  static const char* value()
  {
    return DataType< ::ros_essentials_cpp::RectangleAreaService >::value();
  }
  static const char* value(const ::ros_essentials_cpp::RectangleAreaServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_ESSENTIALS_CPP_MESSAGE_RECTANGLEAREASERVICE_H
